export const OPENAI_COMPATABLE_TOOL_DISPATCHER = 'openai_compatable_tool_dispatcher';

export const MAX_REQUEST_BODY_BYTES = 1_048_576;
export const MAX_TOOL_COUNT = 128;
export const MAX_TOOL_SCHEMA_BYTES = 262_144;
export const MAX_IMAGE_DATA_BYTES = 20 * 1_048_576;
export const MAX_TRANSCRIPT_BYTES = 2 * 1_048_576;
export const MAX_GENERATED_TOOL_CALLS = 32;
export const MAX_INVALID_TOOL_ATTEMPTS = 3;
export const REQUEST_TIMEOUT_MS = 120_000;
export const TOOL_COLLECTION_QUIET_MS = 250;
export const TOOL_COLLECTION_DEADLINE_MS = 2_000;
export const MAX_VALIDATION_ERRORS = 5;
export const MAX_VALIDATION_ERROR_BYTES = 2_048;

export const TRANSCRIPT_SYSTEM_START = '<OPENAI_SYSTEM_RECORDS_JSON>';
export const TRANSCRIPT_SYSTEM_END = '</OPENAI_SYSTEM_RECORDS_JSON>';
export const TRANSCRIPT_TOOLS_START = '<EXTERNAL_TOOLS_JSON>';
export const TRANSCRIPT_TOOLS_END = '</EXTERNAL_TOOLS_JSON>';
export const TRANSCRIPT_MESSAGES_START = '<OPENAI_TRANSCRIPT_JSON>';
export const TRANSCRIPT_MESSAGES_END = '</OPENAI_TRANSCRIPT_JSON>';
